api:
  endpoint: "https://opencode.ai/zen/go/v1"
  model: "deepseek-v4-flash"
  api_key: "sk-bmbJZeXN9mVmbAQW3FbnAb8mJGfZjRLVWdpphLdl2b0o58C1UjAGOFr58vWWdJ92"

default_agent: main
agents_directory: agents
