#!/usr/bin/env python3
"""Write ``configuration.example.yaml`` from the configuration schema.

The reference file used to be maintained by hand, which meant it was a second copy of the
defaults kept in step with the first by nothing but attention. It drifted: settings that had
been renamed were still documented under their old names, and settings that had been added
were not documented at all. A file that claims to be the complete reference and is not is
worse than no file, because a reader has no way to tell which parts are still true.

So it is generated. Every value in it is read from the Pydantic fields, and every explanation
from those fields' ``description`` (and, for the individual tunables, from
:class:`~xeac.base.tuning.Default`). Drift is no longer possible in the direction that matters:
the file cannot describe a setting the code does not have, or miss one it does.

The emitter is ``ruamel.yaml`` rather than the ``pyyaml`` the rest of the harness reads with,
because a comment is the entire point of this file and ``pyyaml`` cannot write one — it parses
comments away and has no API to attach them. Given a library that can, the only thing left to
do by hand is wrap the prose to a column, which is ``textwrap``. Building the document as a
tree and letting the library decide indentation, quoting, and block style is what keeps this
script from being a YAML writer with a schema walker bolted on.

    python scripts/generate_configuration_reference.py           # write it
    python scripts/generate_configuration_reference.py --check   # fail if it is stale
"""

from __future__ import annotations

import argparse
import io
import sys
import textwrap
from pathlib import Path

from ruamel.yaml import YAML
from ruamel.yaml.comments import CommentedMap
from ruamel.yaml.representer import RoundTripRepresenter

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from xeac.base.configuration_schema import Setting, settings  # noqa: E402

OUTPUT = ROOT / "configuration.example.yaml"
COMMENT_WIDTH = 96

PREAMBLE = """\
XEAC — every setting, with what it is for and what it ships at.

GENERATED by scripts/generate_configuration_reference.py from the configuration schema. Edit
the `Field(description=...)` beside a setting, or the `Default(...)` beside a tunable, and
regenerate — an edit made here is overwritten.

This is a REFERENCE, not a starting point. Copying it wholesale would pin every value to this
release's defaults, so a later release could never move any of them. The file XEAC creates at
~/.config/xeac/configuration.yaml stays short on purpose, holding only what you changed.

`xeac configure --all` prints the same information from the running code, with what YOUR
machine is currently set to alongside each default. `xeac configure <path>` reads one setting
and `xeac configure <path> <value>` writes it. A name this file does not list is refused
rather than written and ignored.

Credentials can also come from the environment, which wins over anything written here — so a
secret never has to be on disk. NEVER commit a filled-in copy of this file.
"""


def _explicit_null(representer, _value):
    """Write ``null`` rather than an empty value.

    A bare `umask:` is valid YAML for null and reads as an unfinished line — in a file whose
    job is to say what each setting holds, the word is the point."""
    return representer.represent_scalar("tag:yaml.org,2002:null", "null")


RoundTripRepresenter.add_representer(type(None), _explicit_null)


def _is_section(path: str, everything: list[Setting]) -> bool:
    """Whether anything is nested under this path, making it a place to put settings rather
    than a setting itself."""
    return any(other.path.startswith(path + ".") for other in everything)


def _wrapped(text: str, indent: int) -> str:
    return "\n".join(textwrap.wrap(text, width=max(40, COMMENT_WIDTH - indent)))


def document() -> CommentedMap:
    """The reference as a comment-carrying tree, ready for the emitter to lay out."""
    everything = settings()
    root = CommentedMap()
    sections: dict[str, CommentedMap] = {"": root}
    root.yaml_set_start_comment(PREAMBLE)

    for setting in everything:
        parent_path, _, name = setting.path.rpartition(".")
        parent = sections[parent_path]
        depth = setting.path.count(".")

        is_section = _is_section(setting.path, everything)
        if is_section:
            sections[setting.path] = parent[name] = CommentedMap()
        elif setting.open_ended:
            parent[name] = {}
        else:
            parent[name] = setting.default

        paragraphs = [setting.about] if setting.about else []
        # Only for a map left empty. `tuning.defaults` is also open-ended, but every name that
        # may go under it is enumerated below it, so saying the keys are the reader's own would
        # be false there.
        if setting.open_ended and not is_section:
            paragraphs.append("Keys here are your own names; there is no fixed set.")
        if paragraphs:
            # A blank line before each top-level section, so the file reads as sections rather
            # than as one wall of keys — and so the first is not run into by the preamble.
            lead = "\n" if depth == 0 else ""
            wrapped = "\n".join(_wrapped(paragraph, 2 * depth) for paragraph in paragraphs)
            parent.yaml_set_comment_before_after_key(
                name, before=lead + wrapped, indent=2 * depth
            )
    return root


def render() -> str:
    yaml = YAML()
    yaml.indent(mapping=2, sequence=4, offset=2)
    # Long comment lines are already wrapped to `COMMENT_WIDTH`; this stops the emitter from
    # folding a long *value* — a URL, a path — onto a second line, where it reads as two keys.
    yaml.width = 4096
    stream = io.StringIO()
    yaml.dump(document(), stream)
    return stream.getvalue()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="exit non-zero if the file on disk differs from what the schema produces",
    )
    arguments = parser.parse_args()
    rendered = render()
    if arguments.check:
        existing = OUTPUT.read_text() if OUTPUT.exists() else ""
        if existing != rendered:
            print(
                f"{OUTPUT.relative_to(ROOT)} is out of date with the configuration schema. "
                "Run: python scripts/generate_configuration_reference.py",
                file=sys.stderr,
            )
            return 1
        print("configuration reference is up to date")
        return 0
    OUTPUT.write_text(rendered)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
