#!/usr/bin/env python3
"""Write ``configuration.example.yaml`` from the configuration schema.

The reference file used to be maintained by hand, which meant it was a second copy of the
defaults kept in step with the first by nothing but attention. It drifted: settings that had
been renamed were still documented under their old names, and settings that had been added
were not documented at all. A file that claims to be the complete reference and is not is
worse than no file, because a reader has no way to tell which parts are still true.

So it is generated. Every value in it is read from the Pydantic fields, and every explanation
from those fields' ``description`` (and, for the individual tunables, from
:class:`~xeac.base.tuning.Default`). Drift is no longer possible in the direction that matters:
the file cannot describe a setting the code does not have, or miss one it does.

    python scripts/generate_configuration_reference.py           # write it
    python scripts/generate_configuration_reference.py --check   # fail if it is stale
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from xeac.base.configuration_schema import Setting, settings  # noqa: E402

OUTPUT = ROOT / "configuration.example.yaml"
COMMENT_WIDTH = 96

PREAMBLE = """\
# XEAC — every setting, with what it is for and what it ships at.
#
# GENERATED by scripts/generate_configuration_reference.py from the configuration schema. Edit
# the `Field(description=...)` beside a setting, or the `Default(...)` beside a tunable, and
# regenerate — an edit made here is overwritten.
#
# This is a REFERENCE, not a starting point. Copying it wholesale would pin every value to this
# release's defaults, so a later release could never move any of them. The file XEAC creates at
# ~/.config/xeac/configuration.yaml stays short on purpose, holding only what you changed.
#
# `xeac configure --all` prints the same information from the running code, with what YOUR
# machine is currently set to alongside each default. `xeac configure <path>` reads one setting
# and `xeac configure <path> <value>` writes it. A name this file does not list is refused
# rather than written and ignored.
#
# Credentials can also come from the environment, which wins over anything written here — so a
# secret never has to be on disk. NEVER commit a filled-in copy of this file.
"""


def _children_of(path: str, everything: list[Setting]) -> bool:
    marker = path + "."
    return any(other.path.startswith(marker) for other in everything)


def _comment(text: str, indent: str) -> list[str]:
    if not text:
        return []
    width = max(40, COMMENT_WIDTH - len(indent))
    return [f"{indent}# {line}" for line in textwrap.wrap(text, width=width)]


def _scalar(value: object) -> str:
    """One value, as YAML would hold it, on a single line."""
    dumped = yaml.safe_dump(value, default_flow_style=True, allow_unicode=True, sort_keys=False)
    return dumped.strip().removesuffix("...").strip()


def _block(value: object, indent: str) -> list[str]:
    """A list or mapping, laid out over several lines so it stays readable at a glance."""
    dumped = yaml.safe_dump(value, default_flow_style=False, allow_unicode=True, sort_keys=False)
    return [f"{indent}{line}" if line.strip() else line for line in dumped.rstrip().splitlines()]


def render() -> str:
    everything = settings()
    lines = [PREAMBLE.rstrip(), ""]
    previous_depth = -1
    for setting in everything:
        depth = setting.path.count(".")
        name = setting.path.rsplit(".", 1)[-1]
        indent = "  " * depth
        # A blank line before each new top-level section, so the file reads as sections rather
        # than as one wall of keys.
        if depth == 0 and previous_depth >= 0:
            lines.append("")
        previous_depth = depth
        lines.extend(_comment(setting.about, indent))
        if _children_of(setting.path, everything):
            lines.append(f"{indent}{name}:")
            continue
        if setting.open_ended:
            lines.append(f"{indent}# Keys here are your own names; there is no fixed set.")
            lines.append(f"{indent}{name}: {{}}")
            continue
        if isinstance(setting.default, (list, dict)) and setting.default:
            lines.append(f"{indent}{name}:")
            lines.extend(_block(setting.default, indent + "  "))
            continue
        lines.append(f"{indent}{name}: {_scalar(setting.default)}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="exit non-zero if the file on disk differs from what the schema produces",
    )
    arguments = parser.parse_args()
    rendered = render()
    if arguments.check:
        existing = OUTPUT.read_text() if OUTPUT.exists() else ""
        if existing != rendered:
            print(
                f"{OUTPUT.relative_to(ROOT)} is out of date with the configuration schema. "
                "Run: python scripts/generate_configuration_reference.py",
                file=sys.stderr,
            )
            return 1
        print("configuration reference is up to date")
        return 0
    OUTPUT.write_text(rendered)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
